// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_routingpolicyrule

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RoutingpolicyruleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"action": schema.StringAttribute{
				Required:            true,
				Description:         "* `permit` - Permit\n* `deny` - Deny",
				MarkdownDescription: "* `permit` - Permit\n* `deny` - Deny",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"permit",
						"deny",
					),
				},
			},
			"comments": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"continue_entry": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(500),
				},
			},
			"display": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "A unique integer value identifying this routing policy rule.",
				MarkdownDescription: "A unique integer value identifying this routing policy rule.",
			},
			"index": schema.Int64Attribute{
				Required: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"match_aspath_list": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"match_community": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"match_community_list": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"match_custom": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Provide a JSON-serialized object.",
				MarkdownDescription: "Provide a JSON-serialized object.",
			},
			"match_ip_address": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"match_ipv6_address": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"routing_policy": schema.Int64Attribute{
				Required:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"set_actions": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Provide a JSON-serialized object.",
				MarkdownDescription: "Provide a JSON-serialized object.",
			},
			"tags": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
		},
	}
}

type RoutingpolicyruleModel struct {
	Action             types.String `tfsdk:"action"`
	Comments           types.String `tfsdk:"comments"`
	ContinueEntry      types.Int64  `tfsdk:"continue_entry"`
	Description        types.String `tfsdk:"description"`
	Display            types.String `tfsdk:"display"`
	Id                 types.Int64  `tfsdk:"id"`
	Index              types.Int64  `tfsdk:"index"`
	MatchAspathList    types.List   `tfsdk:"match_aspath_list"`
	MatchCommunity     types.List   `tfsdk:"match_community"`
	MatchCommunityList types.List   `tfsdk:"match_community_list"`
	MatchCustom        types.String `tfsdk:"match_custom"`
	MatchIpAddress     types.List   `tfsdk:"match_ip_address"`
	MatchIpv6Address   types.List   `tfsdk:"match_ipv6_address"`
	RoutingPolicy      types.Int64  `tfsdk:"routing_policy"`
	SetActions         types.String `tfsdk:"set_actions"`
	Tags               types.List   `tfsdk:"tags"`
}
