// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_prefix_list_rule

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-nettypes/cidrtypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PrefixListRuleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"action": schema.StringAttribute{
				Required:            true,
				Description:         "* `permit` - Permit\n* `deny` - Deny",
				MarkdownDescription: "* `permit` - Permit\n* `deny` - Deny",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"permit",
						"deny",
					),
				},
			},
			"comments": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"created": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"display": schema.StringAttribute{
				Computed: true,
			},
			"ge": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 128),
				},
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "A unique integer value identifying this prefix list rule.",
				MarkdownDescription: "A unique integer value identifying this prefix list rule.",
			},
			"index": schema.Int64Attribute{
				Required: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"last_updated": schema.StringAttribute{
				Computed: true,
			},
			"le": schema.Int64Attribute{
				Optional: true,
				Computed: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 128),
				},
			},
			"prefix": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"prefix_custom": schema.StringAttribute{
				CustomType: cidrtypes.IPPrefixType{},
				Optional:   true,
				Computed:   true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"prefix_list": schema.Int64Attribute{
				Required:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"tags": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
		},
	}
}

type PrefixListRuleModel struct {
	Action       types.String       `tfsdk:"action"`
	Comments     types.String       `tfsdk:"comments"`
	Created      types.String       `tfsdk:"created"`
	Description  types.String       `tfsdk:"description"`
	Display      types.String       `tfsdk:"display"`
	Ge           types.Int64        `tfsdk:"ge"`
	Id           types.Int64        `tfsdk:"id"`
	Index        types.Int64        `tfsdk:"index"`
	LastUpdated  types.String       `tfsdk:"last_updated"`
	Le           types.Int64        `tfsdk:"le"`
	Prefix       types.Int64        `tfsdk:"prefix"`
	PrefixCustom cidrtypes.IPPrefix `tfsdk:"prefix_custom"`
	PrefixList   types.Int64        `tfsdk:"prefix_list"`
	Tags         types.List         `tfsdk:"tags"`
}
