// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_prefixlist

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PrefixlistResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"comments": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"display": schema.StringAttribute{
				Computed: true,
			},
			"family": schema.StringAttribute{
				Required:            true,
				Description:         "* `ipv4` - IPv4\n* `ipv6` - IPv6",
				MarkdownDescription: "* `ipv4` - IPv4\n* `ipv6` - IPv6",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"ipv4",
						"ipv6",
					),
				},
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "A unique integer value identifying this prefix list.",
				MarkdownDescription: "A unique integer value identifying this prefix list.",
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 100),
				},
			},
			"tags": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type PrefixlistModel struct {
	Comments    types.String `tfsdk:"comments"`
	Description types.String `tfsdk:"description"`
	Display     types.String `tfsdk:"display"`
	Family      types.String `tfsdk:"family"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Tags        types.List   `tfsdk:"tags"`
	Url         types.String `tfsdk:"url"`
}
