// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_session

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SessionResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"comments": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"device": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"export_policies": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"id": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "A unique integer value identifying this bgp session.",
				MarkdownDescription: "A unique integer value identifying this bgp session.",
			},
			"import_policies": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"local_address": schema.Int64Attribute{
				Required:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"local_as": schema.Int64Attribute{
				Required:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"name": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(256),
				},
			},
			"peer_group": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"prefix_list_in": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"prefix_list_out": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"remote_address": schema.Int64Attribute{
				Required:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"remote_as": schema.Int64Attribute{
				Required:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"site": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"status": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "* `offline` - Offline\n* `active` - Active\n* `planned` - Planned\n* `failed` - Failed",
				MarkdownDescription: "* `offline` - Offline\n* `active` - Active\n* `planned` - Planned\n* `failed` - Failed",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"offline",
						"active",
						"planned",
						"failed",
					),
				},
			},
			"tags": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"tenant": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"virtualmachine": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
		},
	}
}

type SessionModel struct {
	Comments       types.String `tfsdk:"comments"`
	Description    types.String `tfsdk:"description"`
	Device         types.Int64  `tfsdk:"device"`
	ExportPolicies types.List   `tfsdk:"export_policies"`
	Id             types.Int64  `tfsdk:"id"`
	ImportPolicies types.List   `tfsdk:"import_policies"`
	LocalAddress   types.Int64  `tfsdk:"local_address"`
	LocalAs        types.Int64  `tfsdk:"local_as"`
	Name           types.String `tfsdk:"name"`
	PeerGroup      types.Int64  `tfsdk:"peer_group"`
	PrefixListIn   types.Int64  `tfsdk:"prefix_list_in"`
	PrefixListOut  types.Int64  `tfsdk:"prefix_list_out"`
	RemoteAddress  types.Int64  `tfsdk:"remote_address"`
	RemoteAs       types.Int64  `tfsdk:"remote_as"`
	Site           types.Int64  `tfsdk:"site"`
	Status         types.String `tfsdk:"status"`
	Tags           types.List   `tfsdk:"tags"`
	Tenant         types.Int64  `tfsdk:"tenant"`
	Virtualmachine types.Int64  `tfsdk:"virtualmachine"`
}
