// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasources

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func PrefixListDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"comments": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Computed: true,
			},
			"display": schema.StringAttribute{
				Computed: true,
			},
			"family": schema.StringAttribute{
				Computed:            true,
				Description:         "* `ipv4` - IPv4\n* `ipv6` - IPv6",
				MarkdownDescription: "* `ipv4` - IPv4\n* `ipv6` - IPv6",
			},
			"id": schema.Int64Attribute{
				Required:            true,
				Description:         "A unique integer value identifying this prefix list.",
				MarkdownDescription: "A unique integer value identifying this prefix list.",
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"tags": schema.ListAttribute{
				ElementType: types.StringType,
				Computed:    true,
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type PrefixListModel struct {
	Comments    types.String `tfsdk:"comments"`
	Description types.String `tfsdk:"description"`
	Display     types.String `tfsdk:"display"`
	Family      types.String `tfsdk:"family"`
	Id          types.Int64  `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Tags        types.List   `tfsdk:"tags"`
	Url         types.String `tfsdk:"url"`
}
