// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasources

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func PrefixListsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"created__empty": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"created__gt": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"created__gte": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"created__lt": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"created__lte": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"created__n": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"created_by_request": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"description": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__empty": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"description__ic": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__ie": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__iew": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__iregex": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__isw": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__n": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__nic": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__nie": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__niew": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__nisw": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"description__regex": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"family": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "* `ipv4` - IPv4\n* `ipv6` - IPv6",
				MarkdownDescription: "* `ipv4` - IPv4\n* `ipv6` - IPv6",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"ipv4",
						"ipv6",
						"null",
					),
				},
			},
			"id": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"id__empty": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"id__gt": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"id__gte": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"id__lt": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"id__lte": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"id__n": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"last_updated": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"last_updated__empty": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"last_updated__gt": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"last_updated__gte": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"last_updated__lt": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"last_updated__lte": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"last_updated__n": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"limit": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Number of results to return per page.",
				MarkdownDescription: "Number of results to return per page.",
			},
			"modified_by_request": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"name": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__empty": schema.BoolAttribute{
				Optional: true,
				Computed: true,
			},
			"name__ic": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__ie": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__iew": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__iregex": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__isw": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__n": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__nic": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__nie": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__niew": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__nisw": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name__regex": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"next": schema.StringAttribute{
				Computed: true,
			},
			"offset": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The initial index from which to return the results.",
				MarkdownDescription: "The initial index from which to return the results.",
			},
			"ordering": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Which field to use when ordering the results.",
				MarkdownDescription: "Which field to use when ordering the results.",
			},
			"previous": schema.StringAttribute{
				Computed: true,
			},
			"q": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Search",
				MarkdownDescription: "Search",
			},
			"results": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"comments": schema.StringAttribute{
							Computed: true,
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"display": schema.StringAttribute{
							Computed: true,
						},
						"family": schema.StringAttribute{
							Computed:            true,
							Description:         "* `ipv4` - IPv4\n* `ipv6` - IPv6",
							MarkdownDescription: "* `ipv4` - IPv4\n* `ipv6` - IPv6",
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"tags": schema.ListAttribute{
							ElementType: types.StringType,
							Computed:    true,
						},
						"url": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ResultsType{
						ObjectType: types.ObjectType{
							AttrTypes: ResultsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"tag": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"tag__n": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"tag_id": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"tag_id__n": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"updated_by_request": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type PrefixListsModel struct {
	Created            types.List   `tfsdk:"created"`
	Created_Empty      types.List   `tfsdk:"created__empty"`
	Created_Gt         types.List   `tfsdk:"created__gt"`
	Created_Gte        types.List   `tfsdk:"created__gte"`
	Created_Lt         types.List   `tfsdk:"created__lt"`
	Created_Lte        types.List   `tfsdk:"created__lte"`
	Created_N          types.List   `tfsdk:"created__n"`
	CreatedByRequest   types.String `tfsdk:"created_by_request"`
	Description        types.List   `tfsdk:"description"`
	Description_Empty  types.Bool   `tfsdk:"description__empty"`
	Description_Ic     types.List   `tfsdk:"description__ic"`
	Description_Ie     types.List   `tfsdk:"description__ie"`
	Description_Iew    types.List   `tfsdk:"description__iew"`
	Description_Iregex types.List   `tfsdk:"description__iregex"`
	Description_Isw    types.List   `tfsdk:"description__isw"`
	Description_N      types.List   `tfsdk:"description__n"`
	Description_Nic    types.List   `tfsdk:"description__nic"`
	Description_Nie    types.List   `tfsdk:"description__nie"`
	Description_Niew   types.List   `tfsdk:"description__niew"`
	Description_Nisw   types.List   `tfsdk:"description__nisw"`
	Description_Regex  types.List   `tfsdk:"description__regex"`
	Family             types.String `tfsdk:"family"`
	Id                 types.List   `tfsdk:"id"`
	Id_Empty           types.Bool   `tfsdk:"id__empty"`
	Id_Gt              types.List   `tfsdk:"id__gt"`
	Id_Gte             types.List   `tfsdk:"id__gte"`
	Id_Lt              types.List   `tfsdk:"id__lt"`
	Id_Lte             types.List   `tfsdk:"id__lte"`
	Id_N               types.List   `tfsdk:"id__n"`
	LastUpdated        types.List   `tfsdk:"last_updated"`
	LastUpdated_Empty  types.List   `tfsdk:"last_updated__empty"`
	LastUpdated_Gt     types.List   `tfsdk:"last_updated__gt"`
	LastUpdated_Gte    types.List   `tfsdk:"last_updated__gte"`
	LastUpdated_Lt     types.List   `tfsdk:"last_updated__lt"`
	LastUpdated_Lte    types.List   `tfsdk:"last_updated__lte"`
	LastUpdated_N      types.List   `tfsdk:"last_updated__n"`
	Limit              types.Int64  `tfsdk:"limit"`
	ModifiedByRequest  types.String `tfsdk:"modified_by_request"`
	Name               types.List   `tfsdk:"name"`
	Name_Empty         types.Bool   `tfsdk:"name__empty"`
	Name_Ic            types.List   `tfsdk:"name__ic"`
	Name_Ie            types.List   `tfsdk:"name__ie"`
	Name_Iew           types.List   `tfsdk:"name__iew"`
	Name_Iregex        types.List   `tfsdk:"name__iregex"`
	Name_Isw           types.List   `tfsdk:"name__isw"`
	Name_N             types.List   `tfsdk:"name__n"`
	Name_Nic           types.List   `tfsdk:"name__nic"`
	Name_Nie           types.List   `tfsdk:"name__nie"`
	Name_Niew          types.List   `tfsdk:"name__niew"`
	Name_Nisw          types.List   `tfsdk:"name__nisw"`
	Name_Regex         types.List   `tfsdk:"name__regex"`
	Next               types.String `tfsdk:"next"`
	Offset             types.Int64  `tfsdk:"offset"`
	Ordering           types.String `tfsdk:"ordering"`
	Previous           types.String `tfsdk:"previous"`
	Q                  types.String `tfsdk:"q"`
	Results            types.List   `tfsdk:"results"`
	Tag                types.List   `tfsdk:"tag"`
	Tag_N              types.List   `tfsdk:"tag__n"`
	TagId              types.List   `tfsdk:"tag_id"`
	TagId_N            types.List   `tfsdk:"tag_id__n"`
	UpdatedByRequest   types.String `tfsdk:"updated_by_request"`
}

var _ basetypes.ObjectTypable = ResultsType{}

type ResultsType struct {
	basetypes.ObjectType
}

func (t ResultsType) Equal(o attr.Type) bool {
	other, ok := o.(ResultsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ResultsType) String() string {
	return "ResultsType"
}

func (t ResultsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	commentsAttribute, ok := attributes["comments"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`comments is missing from object`)

		return nil, diags
	}

	commentsVal, ok := commentsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`comments expected to be basetypes.StringValue, was: %T`, commentsAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	displayAttribute, ok := attributes["display"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`display is missing from object`)

		return nil, diags
	}

	displayVal, ok := displayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`display expected to be basetypes.StringValue, was: %T`, displayAttribute))
	}

	familyAttribute, ok := attributes["family"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`family is missing from object`)

		return nil, diags
	}

	familyVal, ok := familyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`family expected to be basetypes.StringValue, was: %T`, familyAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	tagsAttribute, ok := attributes["tags"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tags is missing from object`)

		return nil, diags
	}

	tagsVal, ok := tagsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tags expected to be basetypes.ListValue, was: %T`, tagsAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return nil, diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ResultsValue{
		Comments:    commentsVal,
		Description: descriptionVal,
		Display:     displayVal,
		Family:      familyVal,
		Id:          idVal,
		Name:        nameVal,
		Tags:        tagsVal,
		Url:         urlVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewResultsValueNull() ResultsValue {
	return ResultsValue{
		state: attr.ValueStateNull,
	}
}

func NewResultsValueUnknown() ResultsValue {
	return ResultsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewResultsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ResultsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ResultsValue Attribute Value",
				"While creating a ResultsValue value, a missing attribute value was detected. "+
					"A ResultsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ResultsValue Attribute Type",
				"While creating a ResultsValue value, an invalid attribute value was detected. "+
					"A ResultsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ResultsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ResultsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ResultsValue Attribute Value",
				"While creating a ResultsValue value, an extra attribute value was detected. "+
					"A ResultsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ResultsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewResultsValueUnknown(), diags
	}

	commentsAttribute, ok := attributes["comments"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`comments is missing from object`)

		return NewResultsValueUnknown(), diags
	}

	commentsVal, ok := commentsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`comments expected to be basetypes.StringValue, was: %T`, commentsAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewResultsValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	displayAttribute, ok := attributes["display"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`display is missing from object`)

		return NewResultsValueUnknown(), diags
	}

	displayVal, ok := displayAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`display expected to be basetypes.StringValue, was: %T`, displayAttribute))
	}

	familyAttribute, ok := attributes["family"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`family is missing from object`)

		return NewResultsValueUnknown(), diags
	}

	familyVal, ok := familyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`family expected to be basetypes.StringValue, was: %T`, familyAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewResultsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.Int64Value, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewResultsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	tagsAttribute, ok := attributes["tags"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`tags is missing from object`)

		return NewResultsValueUnknown(), diags
	}

	tagsVal, ok := tagsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`tags expected to be basetypes.ListValue, was: %T`, tagsAttribute))
	}

	urlAttribute, ok := attributes["url"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`url is missing from object`)

		return NewResultsValueUnknown(), diags
	}

	urlVal, ok := urlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`url expected to be basetypes.StringValue, was: %T`, urlAttribute))
	}

	if diags.HasError() {
		return NewResultsValueUnknown(), diags
	}

	return ResultsValue{
		Comments:    commentsVal,
		Description: descriptionVal,
		Display:     displayVal,
		Family:      familyVal,
		Id:          idVal,
		Name:        nameVal,
		Tags:        tagsVal,
		Url:         urlVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewResultsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ResultsValue {
	object, diags := NewResultsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewResultsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ResultsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewResultsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewResultsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewResultsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewResultsValueMust(ResultsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ResultsType) ValueType(ctx context.Context) attr.Value {
	return ResultsValue{}
}

var _ basetypes.ObjectValuable = ResultsValue{}

type ResultsValue struct {
	Comments    basetypes.StringValue `tfsdk:"comments"`
	Description basetypes.StringValue `tfsdk:"description"`
	Display     basetypes.StringValue `tfsdk:"display"`
	Family      basetypes.StringValue `tfsdk:"family"`
	Id          basetypes.Int64Value  `tfsdk:"id"`
	Name        basetypes.StringValue `tfsdk:"name"`
	Tags        basetypes.ListValue   `tfsdk:"tags"`
	Url         basetypes.StringValue `tfsdk:"url"`
	state       attr.ValueState
}

func (v ResultsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["comments"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["display"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["family"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["tags"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["url"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.Comments.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["comments"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Display.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["display"] = val

		val, err = v.Family.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["family"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Tags.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["tags"] = val

		val, err = v.Url.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["url"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ResultsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ResultsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ResultsValue) String() string {
	return "ResultsValue"
}

func (v ResultsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var tagsVal basetypes.ListValue
	switch {
	case v.Tags.IsUnknown():
		tagsVal = types.ListUnknown(types.StringType)
	case v.Tags.IsNull():
		tagsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		tagsVal, d = types.ListValue(types.StringType, v.Tags.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"comments":    basetypes.StringType{},
			"description": basetypes.StringType{},
			"display":     basetypes.StringType{},
			"family":      basetypes.StringType{},
			"id":          basetypes.Int64Type{},
			"name":        basetypes.StringType{},
			"tags": basetypes.ListType{
				ElemType: types.StringType,
			},
			"url": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"comments":    basetypes.StringType{},
		"description": basetypes.StringType{},
		"display":     basetypes.StringType{},
		"family":      basetypes.StringType{},
		"id":          basetypes.Int64Type{},
		"name":        basetypes.StringType{},
		"tags": basetypes.ListType{
			ElemType: types.StringType,
		},
		"url": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"comments":    v.Comments,
			"description": v.Description,
			"display":     v.Display,
			"family":      v.Family,
			"id":          v.Id,
			"name":        v.Name,
			"tags":        tagsVal,
			"url":         v.Url,
		})

	return objVal, diags
}

func (v ResultsValue) Equal(o attr.Value) bool {
	other, ok := o.(ResultsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Comments.Equal(other.Comments) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Display.Equal(other.Display) {
		return false
	}

	if !v.Family.Equal(other.Family) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Tags.Equal(other.Tags) {
		return false
	}

	if !v.Url.Equal(other.Url) {
		return false
	}

	return true
}

func (v ResultsValue) Type(ctx context.Context) attr.Type {
	return ResultsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ResultsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"comments":    basetypes.StringType{},
		"description": basetypes.StringType{},
		"display":     basetypes.StringType{},
		"family":      basetypes.StringType{},
		"id":          basetypes.Int64Type{},
		"name":        basetypes.StringType{},
		"tags": basetypes.ListType{
			ElemType: types.StringType,
		},
		"url": basetypes.StringType{},
	}
}
