// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_peer_group

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func PeerGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"comments": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"display": schema.StringAttribute{
				Computed: true,
			},
			"export_policies": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "A unique integer value identifying this bgp peer group.",
				MarkdownDescription: "A unique integer value identifying this bgp peer group.",
			},
			"import_policies": schema.ListAttribute{
				ElementType: types.Int64Type,
				Optional:    true,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 100),
				},
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type PeerGroupModel struct {
	Comments       types.String `tfsdk:"comments"`
	Description    types.String `tfsdk:"description"`
	Display        types.String `tfsdk:"display"`
	ExportPolicies types.List   `tfsdk:"export_policies"`
	Id             types.Int64  `tfsdk:"id"`
	ImportPolicies types.List   `tfsdk:"import_policies"`
	Name           types.String `tfsdk:"name"`
	Url            types.String `tfsdk:"url"`
}
