// Code generated by internal/provider/gen DO NOT EDIT.

package provider

import (
	"context"
	"net/http"

	"github.com/ffddorf/terraform-provider-netbox-bgp/internal/resource_prefixlistrule"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &PrefixlistruleResource{}
var _ resource.ResourceWithImportState = &PrefixlistruleResource{}

func NewPrefixlistruleResource() resource.Resource {
	return &PrefixlistruleResource{}
}

// SessionResource defines the resource implementation.
type PrefixlistruleResource struct {
	client *ProviderClient
}

// Metadata implements resource.Resource.
func (*PrefixlistruleResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_prefixlistrule"
}

// Schema implements resource.Resource.
func (*PrefixlistruleResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resource_prefixlistrule.PrefixlistruleResourceSchema(ctx)
}

func (r *PrefixlistruleResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = configureResourceClient(req, resp)
}

// Read implements resource.Resource.
func (r *PrefixlistruleResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data resource_prefixlistrule.PrefixlistruleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListRuleRetrieveWithResponse(ctx, int(data.Id.ValueInt64()))
	resp.Diagnostics.Append(MaybeAPIError("failed to fetch prefixlistrule", err, parsed.JSON200, parsed.HTTPResponse, parsed.Body)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, parsed.JSON200, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Create implements resource.Resource.
func (r *PrefixlistruleResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data resource_prefixlistrule.PrefixlistruleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := data.ToAPIModel(ctx, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListRuleCreateWithResponse(ctx, params)
	resp.Diagnostics.Append(MaybeAPIError("failed to create prefixlistrule", err, parsed.JSON201, parsed.HTTPResponse, parsed.Body)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, parsed.JSON201, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Update implements resource.Resource.
func (r *PrefixlistruleResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data resource_prefixlistrule.PrefixlistruleModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	var id int64
	resp.Diagnostics.Append(req.State.GetAttribute(ctx, path.Root("id"), &id)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := data.ToAPIModel(ctx, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	parsed, err := r.client.PluginsBgpPrefixListRuleUpdateWithResponse(ctx, int(id), params)
	resp.Diagnostics.Append(MaybeAPIError("failed to update prefixlistrule", err, parsed.JSON200, parsed.HTTPResponse, parsed.Body)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, parsed.JSON200, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Delete implements resource.Resource.
func (r *PrefixlistruleResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data resource_prefixlistrule.PrefixlistruleModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListRuleDestroyWithResponse(ctx, int(data.Id.ValueInt64()))
	toCheck := parsed
	if parsed.StatusCode() != http.StatusNoContent {
		toCheck = nil // response not usable
	}
	resp.Diagnostics.Append(MaybeAPIError("failed to delete prefixlistrule", err, toCheck, parsed.HTTPResponse, parsed.Body)...)
}

// ImportState implements resource.ResourceWithImportState.
func (p *PrefixlistruleResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByInt64ID(ctx, req, resp)
}
