// Code generated by internal/provider/gen DO NOT EDIT.

package provider

import (
	"context"
	"net/http"

	"github.com/ffddorf/terraform-provider-netbox-bgp/internal/resource_prefix_list"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &PrefixListResource{}
var _ resource.ResourceWithImportState = &PrefixListResource{}

func NewPrefixListResource() resource.Resource {
	return &PrefixListResource{}
}

// SessionResource defines the resource implementation.
type PrefixListResource struct {
	client *ProviderClient
}

// Metadata implements resource.Resource.
func (*PrefixListResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_prefix_list"
}

// Schema implements resource.Resource.
func (*PrefixListResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resource_prefix_list.PrefixListResourceSchema(ctx)
}

func (r *PrefixListResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = configureResourceClient(req, resp)
}

// Read implements resource.Resource.
func (r *PrefixListResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data resource_prefix_list.PrefixListModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListRetrieveWithResponse(ctx, int(data.Id.ValueInt64()))
	resp.Diagnostics.Append(MaybeAPIError("failed to fetch prefix_list", err, parsed.JSON200, parsed.HTTPResponse, parsed.Body)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, parsed.JSON200, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Create implements resource.Resource.
func (r *PrefixListResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data resource_prefix_list.PrefixListModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := data.ToAPIModel(ctx, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListCreateWithResponse(ctx, params)
	resp.Diagnostics.Append(MaybeAPIError("failed to create prefix_list", err, parsed.JSON201, parsed.HTTPResponse, parsed.Body)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, parsed.JSON201, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Update implements resource.Resource.
func (r *PrefixListResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data resource_prefix_list.PrefixListModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	var id int64
	resp.Diagnostics.Append(req.State.GetAttribute(ctx, path.Root("id"), &id)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := data.ToAPIModel(ctx, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	parsed, err := r.client.PluginsBgpPrefixListUpdateWithResponse(ctx, int(id), params)
	resp.Diagnostics.Append(MaybeAPIError("failed to update prefix_list", err, parsed.JSON200, parsed.HTTPResponse, parsed.Body)...)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, parsed.JSON200, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Delete implements resource.Resource.
func (r *PrefixListResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data resource_prefix_list.PrefixListModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListDestroyWithResponse(ctx, int(data.Id.ValueInt64()))
	toCheck := parsed
	if parsed.StatusCode() != http.StatusNoContent {
		toCheck = nil // response not usable
	}
	resp.Diagnostics.Append(MaybeAPIError("failed to delete prefix_list", err, toCheck, parsed.HTTPResponse, parsed.Body)...)
}

// ImportState implements resource.ResourceWithImportState.
func (p *PrefixListResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByInt64ID(ctx, req, resp)
}
