// Code generated by internal/provider/gen DO NOT EDIT.

package provider

import (
	"context"
	"net/http"

	"github.com/ffddorf/terraform-provider-netbox-bgp/internal/resource_prefixlist"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &PrefixlistResource{}
var _ resource.ResourceWithImportState = &PrefixlistResource{}

func NewPrefixlistResource() resource.Resource {
	return &PrefixlistResource{}
}

// SessionResource defines the resource implementation.
type PrefixlistResource struct {
	client *ProviderClient
}

// Metadata implements resource.Resource.
func (*PrefixlistResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_prefixlist"
}

// Schema implements resource.Resource.
func (*PrefixlistResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = resource_prefixlist.PrefixlistResourceSchema(ctx)
}

func (r *PrefixlistResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	r.client = configureResourceClient(req, resp)
}

// Read implements resource.Resource.
func (r *PrefixlistResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data resource_prefixlist.PrefixlistModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListRetrieveWithResponse(ctx, int(data.Id.ValueInt64()))
	res := MaybeAPIError("failed to fetch prefixlist", err, parsed.JSON200, parsed.HTTPResponse, parsed.Body, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, res, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Create implements resource.Resource.
func (r *PrefixlistResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data resource_prefixlist.PrefixlistModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := data.ToAPIModel(ctx, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListCreateWithResponse(ctx, params)
	res := MaybeAPIError("failed to create prefixlist", err, parsed.JSON201, parsed.HTTPResponse, parsed.Body, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, res, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Update implements resource.Resource.
func (r *PrefixlistResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data resource_prefixlist.PrefixlistModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	var id int64
	resp.Diagnostics.Append(req.State.GetAttribute(ctx, path.Root("id"), &id)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := data.ToAPIModel(ctx, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}
	parsed, err := r.client.PluginsBgpPrefixListUpdateWithResponse(ctx, int(id), params)
	res := MaybeAPIError("failed to update prefixlist", err, parsed.JSON200, parsed.HTTPResponse, parsed.Body, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	data.FillFromAPIModel(ctx, res, resp.Diagnostics)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

// Delete implements resource.Resource.
func (r *PrefixlistResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data resource_prefixlist.PrefixlistModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	parsed, err := r.client.PluginsBgpPrefixListDestroyWithResponse(ctx, int(data.Id.ValueInt64()))
	toCheck := parsed
	if parsed.StatusCode() != http.StatusNoContent {
		toCheck = nil // response not usable
	}
	MaybeAPIError("failed to delete prefixlist", err, toCheck, parsed.HTTPResponse, parsed.Body, resp.Diagnostics)
}

// ImportState implements resource.ResourceWithImportState.
func (p *PrefixlistResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	importByInt64ID(ctx, req, resp)
}
