// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_aspath_list_rule

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AspathListRuleResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"action": schema.StringAttribute{
				Required:            true,
				Description:         "* `permit` - Permit\n* `deny` - Deny",
				MarkdownDescription: "* `permit` - Permit\n* `deny` - Deny",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"permit",
						"deny",
					),
				},
			},
			"aspath_list": schema.Int64Attribute{
				Required:            true,
				Description:         "Reference to foreign ID",
				MarkdownDescription: "Reference to foreign ID",
			},
			"comments": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"created": schema.StringAttribute{
				Computed: true,
			},
			"description": schema.StringAttribute{
				Optional: true,
				Computed: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(200),
				},
			},
			"display": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "A unique integer value identifying this as path list rule.",
				MarkdownDescription: "A unique integer value identifying this as path list rule.",
			},
			"index": schema.Int64Attribute{
				Required: true,
				Validators: []validator.Int64{
					int64validator.Between(0, 2147483647),
				},
			},
			"last_updated": schema.StringAttribute{
				Computed: true,
			},
			"pattern": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"tags": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
		},
	}
}

type AspathListRuleModel struct {
	Action      types.String `tfsdk:"action"`
	AspathList  types.Int64  `tfsdk:"aspath_list"`
	Comments    types.String `tfsdk:"comments"`
	Created     types.String `tfsdk:"created"`
	Description types.String `tfsdk:"description"`
	Display     types.String `tfsdk:"display"`
	Id          types.Int64  `tfsdk:"id"`
	Index       types.Int64  `tfsdk:"index"`
	LastUpdated types.String `tfsdk:"last_updated"`
	Pattern     types.String `tfsdk:"pattern"`
	Tags        types.List   `tfsdk:"tags"`
}
